name: Deploy html to storage account

on:
  workflow_dispatch:
  push:
    branches:
      - "main"


permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with: 
        creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
    - uses: actions/checkout@v2
    - name: wipe
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --source ${{ secrets.STORAGE_CONTAINER_NAME }}
    - name: upload
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --destination ${{ secrets.STORAGE_CONTAINER_NAME }} --source build
    - name: logout
      run: az logout
      if: always()
